// SPDX-License-Identifier: MIT
// Copyright (c) 2026 EoS Project
// ISO/IEC 25000 | ISO/IEC/IEEE 15288:2023

/**
 * @file board_cortex_m0plus.h
 * @brief STM32L072 Cortex-M0+ board configuration
 */

#ifndef BOARD_CORTEX_M0PLUS_H
#define BOARD_CORTEX_M0PLUS_H

#include "eos_hal.h"

#define CORTEX_M0PLUS_FLASH_BASE            0x08000000
#define CORTEX_M0PLUS_FLASH_SIZE            (192*1024)
#define CORTEX_M0PLUS_RAM_BASE              0x20000000
#define CORTEX_M0PLUS_RAM_SIZE              (20*1024)

#define CORTEX_M0PLUS_SLOT_A_ADDR           (CORTEX_M0PLUS_FLASH_BASE + 0x20000)
#define CORTEX_M0PLUS_SLOT_A_SIZE           (CORTEX_M0PLUS_FLASH_SIZE / 3)
#define CORTEX_M0PLUS_SLOT_B_ADDR           (CORTEX_M0PLUS_FLASH_BASE + CORTEX_M0PLUS_FLASH_SIZE / 3 + 0x20000)
#define CORTEX_M0PLUS_SLOT_B_SIZE           (CORTEX_M0PLUS_FLASH_SIZE / 3)
#define CORTEX_M0PLUS_RECOVERY_ADDR         (CORTEX_M0PLUS_FLASH_BASE + 2 * CORTEX_M0PLUS_FLASH_SIZE / 3)
#define CORTEX_M0PLUS_RECOVERY_SIZE         (CORTEX_M0PLUS_FLASH_SIZE / 8)
#define CORTEX_M0PLUS_BOOTCTL_ADDR          (CORTEX_M0PLUS_FLASH_BASE + CORTEX_M0PLUS_FLASH_SIZE - 0x2000)
#define CORTEX_M0PLUS_BOOTCTL_BACKUP_ADDR   (CORTEX_M0PLUS_FLASH_BASE + CORTEX_M0PLUS_FLASH_SIZE - 0x4000)
#define CORTEX_M0PLUS_LOG_ADDR              (CORTEX_M0PLUS_FLASH_BASE + CORTEX_M0PLUS_FLASH_SIZE - 0x6000)

#define CORTEX_M0PLUS_CPU_HZ                32000000
#define CORTEX_M0PLUS_BOARD_ID              0x00A1

void board_cortex_m0plus_early_init(void);
const eos_board_ops_t *board_cortex_m0plus_get_ops(void);

#endif /* BOARD_CORTEX_M0PLUS_H */
